name: 收纳
description: 让物品有灵魂
full_description: '万物皆有灵魂，一起发掘吧<br>
<br>With a lot of features:
<br>- Feature 特色 特征 1
<br>- Feature 2
<br>- Feature 3'
android: https://下载地址.com
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
